APP_NAME: str = "Suzaku_Bot"
APP_YOUTUBE_DOWNLOAD: str = "youtube-dl"

FILE_CONFIGURATION_NAME: str = "config.json"
FILE_LOG: str = f"{APP_NAME}.log"
FOLDER_COGS: str = "cogs"

CONF_PREFIX: str = "prefix"
CONF_TOKEN: str = "token"
CONF_PERMISSIONS: str = "permissions"
CONF_APP_ID: str = "application_id"
CONF_CHANNEL_VOICE: str = "voice_channel_id"
CONF_SYNC_COMMANDS_GLOBALLY: str = "sync_commands_globally"
CONF_OWNERS: str = "owners"
CONF_REPOSITORY_PATH: str = "app_path"
CONF_COOKIES_FROM_BROWSER: str = "firefox"

DISCORD_STATUS_PLAYING: str = "Playing Music!"
DISCORD_STATUS_STOPPED: str = "Stopped"

PATTERN_YOUTUBE_URL: str = r"^https:\/\/(www\.|music\.)?youtube\.com\/watch\?v\=[a-zA-Z0-9-_=]*$"
STR_SUBDIR_DOWNLOADS: str = "downloads"
STR_COOKIES_FILE: str = "cookies.txt"
STR_SQLITE_FILE: str = "sqlite.db"
STR_YOUTUBEDL_ARCHIVE_FILE: str = "_archive.txt"
